// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits the compiled config class source code.
/// </summary>
internal class CompiledConfigEmitter
{
    private const string ExpressionValueType = "Microsoft.Azure.ApiManagement.PolicyToolkit.Authoring.ExpressionValue";

    public string Emit(ConfigInfo config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Compiled config class for <see cref=\"{config.ClassName}\"/>.");
        sb.AppendLine("/// Properties are wrapped in ExpressionValue&lt;T&gt; to support both constants and APIM expressions.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal sealed class {config.ClassName}CompiledConfig");
        sb.AppendLine("{");

        foreach (var prop in config.Properties)
        {
            EmitProperty(sb, prop);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitProperty(StringBuilder sb, PropertyInfo prop)
    {
        var wrappedType = WrapType(prop);
        var requiredModifier = prop.IsRequired ? "required " : "";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// XML name: {prop.XmlName}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public {requiredModifier}{wrappedType} {prop.Name} {{ get; init; }}");
        sb.AppendLine();
    }

    private string WrapType(PropertyInfo prop)
    {
        // For collections, wrap the element type
        if (prop.IsCollection && prop.CollectionElementType is not null)
        {
            var elementType = $"{ExpressionValueType}<{prop.CollectionElementType}>";
            var collectionType = $"global::System.Collections.Generic.IReadOnlyList<{elementType}>";
            return prop.IsNullable ? $"{collectionType}?" : collectionType;
        }

        // For interfaces that will have union types, use the union type
        if (prop.IsInterface)
        {
            // Generate union type name by removing "I" prefix and adding "Union" suffix
            var interfaceName = prop.TypeFullName;
            var lastDot = interfaceName.LastIndexOf('.');
            var simpleName = lastDot >= 0 ? interfaceName.Substring(lastDot + 1) : interfaceName;

            // Remove leading "I" if it's an interface naming convention
            if (simpleName.StartsWith("I", StringComparison.Ordinal) && simpleName.Length > 1 && char.IsUpper(simpleName[1]))
            {
                simpleName = simpleName.Substring(1);
            }

            var unionTypeName = $"{simpleName}Union";
            var ns = lastDot >= 0 ? interfaceName.Substring(0, lastDot) : "";
            var fullUnionType = string.IsNullOrEmpty(ns) ? unionTypeName : $"{ns}.{unionTypeName}";

            return prop.IsNullable ? $"{fullUnionType}?" : fullUnionType;
        }

        // Standard wrapping in ExpressionValue<T>
        var wrappedType = $"{ExpressionValueType}<{prop.TypeFullName}>";
        return prop.IsNullable ? $"{wrappedType}?" : wrappedType;
    }
}
