// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits compiled config class source code (properties only).
/// Extract methods are emitted separately by ConfigExtractorEmitter.
/// </summary>
internal class CompiledConfigEmitter
{
    private const string ExpressionValueType = "Microsoft.Azure.ApiManagement.PolicyToolkit.Authoring.ExpressionValue";
    private const string CompiledConfigNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling.Configs";

    public string Emit(ConfigInfo config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {CompiledConfigNamespace};");
        sb.AppendLine();
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"PolicyConfigGenerator\", \"1.0.0\")]");

        string classModifiers;
        if (config.IsAbstract)
        {
            classModifiers = "public abstract partial class";
        }
        else if (config.HasDerivedClasses)
        {
            classModifiers = "public partial class";
        }
        else
        {
            classModifiers = "public sealed partial class";
        }

        var baseClass = config.BaseTypeName is not null ? $" : {config.BaseTypeName}" : "";
        sb.AppendLine($"{classModifiers} {config.ClassName}{baseClass}");
        sb.AppendLine("{");

        foreach (var prop in config.Properties)
        {
            EmitProperty(sb, prop);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitProperty(StringBuilder sb, PropertyInfo prop)
    {
        var wrappedType = WrapType(prop);
        var requiredModifier = prop.IsRequired ? "required " : "";
        sb.AppendLine($"    public {requiredModifier}{wrappedType} {prop.Name} {{ get; init; }}");
    }

    private string WrapType(PropertyInfo prop)
    {
        // For collections, use IReadOnlyList with the element type (compiled config if nested)
        if (prop.IsCollection && prop.CollectionElementType is not null)
        {
            var elementTypeName = prop.CollectionElementType;
            if (prop.CollectionElementIsCompiledConfig)
            {
                // Extract just the class name and use the compiled config namespace
                var lastDot = elementTypeName.LastIndexOf('.');
                var simpleName = lastDot >= 0 ? elementTypeName.Substring(lastDot + 1) : elementTypeName;
                // Remove "global::" prefix if present
                if (simpleName.StartsWith("global::", StringComparison.Ordinal))
                {
                    simpleName = simpleName.Substring(8);
                }
                elementTypeName = $"{CompiledConfigNamespace}.{simpleName}";
            }
            else if (prop.IsExpressionAllowed)
            {
                // For collections with [ExpressionAllowed] where the element is a simple type,
                // wrap the element type in ExpressionValue<T>
                elementTypeName = $"{ExpressionValueType}<{elementTypeName}>";
            }
            
            var collectionType = $"global::System.Collections.Generic.IReadOnlyList<{elementTypeName}>";
            return prop.IsNullable ? $"{collectionType}?" : collectionType;
        }

        // For interfaces that will have union types, use the union type
        if (prop.IsInterface)
        {
            // Generate union type name by removing "I" prefix and adding "Union" suffix
            var interfaceName = prop.TypeFullName;
            var lastDot = interfaceName.LastIndexOf('.');
            var simpleName = lastDot >= 0 ? interfaceName.Substring(lastDot + 1) : interfaceName;

            // Remove leading "I" if it's an interface naming convention
            if (simpleName.StartsWith("I", StringComparison.Ordinal) && simpleName.Length > 1 && char.IsUpper(simpleName[1]))
            {
                simpleName = simpleName.Substring(1);
            }

            // Union types are in the compiled config namespace
            var unionTypeName = $"{CompiledConfigNamespace}.{simpleName}Union";

            return prop.IsNullable ? $"{unionTypeName}?" : unionTypeName;
        }
        
        // For nested compiled configs (non-collection), use the compiled config type
        if (prop.IsNestedCompiledConfig)
        {
            var typeName = prop.TypeFullName;
            var lastDot = typeName.LastIndexOf('.');
            var simpleName = lastDot >= 0 ? typeName.Substring(lastDot + 1) : typeName;
            // Remove "global::" prefix if present
            if (simpleName.StartsWith("global::", StringComparison.Ordinal))
            {
                simpleName = simpleName.Substring(8);
            }
            var compiledConfigTypeName = $"{CompiledConfigNamespace}.{simpleName}";
            return prop.IsNullable ? $"{compiledConfigTypeName}?" : compiledConfigTypeName;
        }

        // Only wrap in ExpressionValue<T> if [ExpressionAllowed] attribute is present
        if (prop.IsExpressionAllowed)
        {
            var wrappedType = $"{ExpressionValueType}<{prop.TypeFullName}>";
            return prop.IsNullable ? $"{wrappedType}?" : wrappedType;
        }

        // No wrapping - use the type directly
        return prop.IsNullable ? $"{prop.TypeFullName}?" : prop.TypeFullName;
    }
}
