// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits strongly-typed Extract() methods for compiled config classes.
/// Eliminates runtime reflection by generating direct property extraction code.
/// </summary>
internal class ConfigExtractorEmitter
{
    private const string CompiledConfigNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling.Configs";
    private const string CompilingNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling";
    private const string ResultsNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Results";
    private const string DiagnosticsNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling.Diagnostics";
    private const string AuthoringNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Authoring";

    public string Emit(
        ConfigInfo config,
        Dictionary<string, ConfigInfo> configLookup,
        Dictionary<string, List<ConfigInfo>> interfaceImplLookup)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {CompiledConfigNamespace};");
        sb.AppendLine();

        // Emit partial class with Extract methods
        var classModifier = config.IsAbstract ? "abstract " : "sealed ";
        if (config.HasDerivedClasses) classModifier = "";

        // Build inheritance: base class (if any) and IExtractableConfig<T> for non-abstract classes
        var inheritanceList = new List<string>();
        if (config.BaseTypeName is not null)
        {
            inheritanceList.Add(config.BaseTypeName);
        }
        if (!config.IsAbstract)
        {
            inheritanceList.Add($"{CompilingNamespace}.IExtractableConfig<{config.ClassName}>");
        }
        var baseClause = inheritanceList.Count > 0 ? $" : {string.Join(", ", inheritanceList)}" : "";
        sb.AppendLine($"public {classModifier}partial class {config.ClassName}{baseClause}");
        sb.AppendLine("{");

        // Don't emit Extract for abstract classes
        if (!config.IsAbstract)
        {
            // Add 'new' modifier when hiding base class methods (to suppress CS0108)
            // Only needed when base class is non-abstract (has its own Extract methods)
            var baseIsNonAbstract = config.BaseTypeName is not null 
                && configLookup.TryGetValue(config.BaseTypeName, out var baseConfig) 
                && !baseConfig.IsAbstract;
            var newModifier = baseIsNonAbstract ? "new " : "";
            EmitExtractMethod(sb, config, newModifier);
            EmitExtractFromExpressionMethod(sb, config, configLookup, interfaceImplLookup, newModifier);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitExtractMethod(StringBuilder sb, ConfigInfo config, string newModifier)
    {
        sb.AppendLine($"    public {newModifier}static {ResultsNamespace}.Result<{config.ClassName}> Extract(");
        sb.AppendLine($"        global::Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax node,");
        sb.AppendLine($"        {CompilingNamespace}.ICompilationContext context,");
        sb.AppendLine($"        string policyName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (node.ArgumentList.Arguments.Count != 1)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return {ResultsNamespace}.Result<{config.ClassName}>.Failure(");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.Diagnostic.Create(");
        sb.AppendLine($"                    {DiagnosticsNamespace}.CompilationErrors.ArgumentCountMissMatchForPolicy,");
        sb.AppendLine($"                    node.ArgumentList.GetLocation(),");
        sb.AppendLine($"                    policyName));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return ExtractFromExpression(node.ArgumentList.Arguments[0].Expression, context, policyName);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void EmitExtractFromExpressionMethod(
        StringBuilder sb,
        ConfigInfo config,
        Dictionary<string, ConfigInfo> configLookup,
        Dictionary<string, List<ConfigInfo>> interfaceImplLookup,
        string newModifier)
    {
        sb.AppendLine($"    public {newModifier}static {ResultsNamespace}.Result<{config.ClassName}> ExtractFromExpression(");
        sb.AppendLine($"        global::Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression,");
        sb.AppendLine($"        {CompilingNamespace}.ICompilationContext context,");
        sb.AppendLine($"        string policyName)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (expression is not global::Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax objectCreation)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return {ResultsNamespace}.Result<{config.ClassName}>.Failure(");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.Diagnostic.Create(");
        sb.AppendLine($"                    {DiagnosticsNamespace}.CompilationErrors.PolicyArgumentIsNotAnObjectCreation,");
        sb.AppendLine($"                    expression.GetLocation(),");
        sb.AppendLine($"                    policyName,");
        sb.AppendLine($"                    \"{config.ClassName}\"));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        var diagnostics = new global::System.Collections.Generic.List<global::Microsoft.CodeAnalysis.Diagnostic>();");
        sb.AppendLine($"        var syntaxProperties = new global::System.Collections.Generic.Dictionary<string, global::Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax>(global::System.StringComparer.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        foreach (var expr in objectCreation.Initializer?.Expressions ?? [])");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (expr is global::Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax assignment)");
        sb.AppendLine("            {");
        sb.AppendLine("                syntaxProperties[assignment.Left.ToString()] = assignment.Right;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Collect all properties including inherited ones
        var allProperties = GetAllProperties(config, configLookup);

        // Emit property extraction variables
        foreach (var prop in allProperties)
        {
            EmitPropertyExtraction(sb, prop, config, configLookup, interfaceImplLookup);
        }

        // Check for errors
        sb.AppendLine("        if (diagnostics.Count > 0)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return {ResultsNamespace}.Result<{config.ClassName}>.Failure(diagnostics);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Build the config object
        sb.AppendLine($"        return new {config.ClassName}");
        sb.AppendLine("        {");
        foreach (var prop in allProperties)
        {
            sb.AppendLine($"            {prop.Name} = __{prop.Name}__,");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private void EmitPropertyExtraction(
        StringBuilder sb,
        PropertyInfo prop,
        ConfigInfo config,
        Dictionary<string, ConfigInfo> configLookup,
        Dictionary<string, List<ConfigInfo>> interfaceImplLookup)
    {
        var varName = $"__{prop.Name}__";
        var propType = GetPropertyType(prop);

        // Declare variable with default
        sb.AppendLine($"        {propType} {varName} = default!;");
        sb.AppendLine($"        if (syntaxProperties.TryGetValue(\"{prop.Name}\", out var {varName}Syntax))");
        sb.AppendLine("        {");

        if (prop.IsCollection)
        {
            EmitCollectionExtraction(sb, prop, varName, configLookup, interfaceImplLookup);
        }
        else if (prop.IsInterface)
        {
            EmitUnionExtraction(sb, prop, varName, interfaceImplLookup);
        }
        else if (prop.IsNestedCompiledConfig)
        {
            EmitNestedConfigExtraction(sb, prop, varName);
        }
        else if (prop.IsExpressionAllowed)
        {
            EmitExpressionValueExtraction(sb, prop, varName);
        }
        else
        {
            EmitPlainValueExtraction(sb, prop, varName);
        }

        sb.AppendLine("        }");

        // Check required
        if (prop.IsRequired)
        {
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            diagnostics.Add(global::Microsoft.CodeAnalysis.Diagnostic.Create(");
            sb.AppendLine($"                {DiagnosticsNamespace}.CompilationErrors.RequiredParameterNotDefined,");
            sb.AppendLine($"                objectCreation.GetLocation(),");
            sb.AppendLine($"                policyName,");
            sb.AppendLine($"                \"{prop.Name}\"));");
            sb.AppendLine("        }");
        }

        sb.AppendLine();
    }

    private void EmitExpressionValueExtraction(StringBuilder sb, PropertyInfo prop, string varName)
    {
        var innerType = prop.TypeFullName;
        sb.AppendLine($"            var {varName}Result = {CompilingNamespace}.ExpressionProcessor.ProcessToExpressionValue<{innerType}>({varName}Syntax, context);");
        sb.AppendLine($"            if ({varName}Result.IsSuccess)");
        sb.AppendLine("            {");
        sb.AppendLine($"                {varName} = {varName}Result.Value;");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine($"                diagnostics.AddRange({varName}Result.Diagnostics);");
        sb.AppendLine("            }");
    }

    private void EmitPlainValueExtraction(StringBuilder sb, PropertyInfo prop, string varName)
    {
        var innerType = prop.TypeFullName;
        sb.AppendLine($"            var {varName}Result = {CompilingNamespace}.ExpressionProcessor.Process({varName}Syntax, context);");
        sb.AppendLine($"            if ({varName}Result.IsSuccess)");
        sb.AppendLine("            {");

        // Handle type conversion for non-string types
        if (innerType == "global::System.String" || innerType == "string")
        {
            sb.AppendLine($"                {varName} = {varName}Result.Value;");
        }
        else if (innerType == "global::System.Int32" || innerType == "int")
        {
            sb.AppendLine($"                if (int.TryParse({varName}Result.Value, out var {varName}Parsed))");
            sb.AppendLine($"                    {varName} = {varName}Parsed;");
        }
        else if (innerType == "global::System.UInt32" || innerType == "uint")
        {
            sb.AppendLine($"                if (uint.TryParse({varName}Result.Value, out var {varName}Parsed))");
            sb.AppendLine($"                    {varName} = {varName}Parsed;");
        }
        else if (innerType == "global::System.Boolean" || innerType == "bool")
        {
            sb.AppendLine($"                if (bool.TryParse({varName}Result.Value, out var {varName}Parsed))");
            sb.AppendLine($"                    {varName} = {varName}Parsed;");
        }
        else
        {
            sb.AppendLine($"                {varName} = {varName}Result.Value;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine($"                diagnostics.AddRange({varName}Result.Diagnostics);");
        sb.AppendLine("            }");
    }

    private void EmitNestedConfigExtraction(StringBuilder sb, PropertyInfo prop, string varName)
    {
        var configTypeName = GetSimpleTypeName(prop.TypeFullName);
        sb.AppendLine($"            var {varName}Result = {CompiledConfigNamespace}.{configTypeName}.ExtractFromExpression({varName}Syntax, context, policyName);");
        sb.AppendLine($"            if ({varName}Result.IsSuccess)");
        sb.AppendLine("            {");
        sb.AppendLine($"                {varName} = {varName}Result.Value;");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine($"                diagnostics.AddRange({varName}Result.Diagnostics);");
        sb.AppendLine("            }");
    }

    private void EmitUnionExtraction(
        StringBuilder sb,
        PropertyInfo prop,
        string varName,
        Dictionary<string, List<ConfigInfo>> interfaceImplLookup)
    {
        var interfaceName = GetSimpleTypeName(prop.TypeFullName);
        // Remove leading "I" for union name
        var unionBaseName = interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;
        var unionTypeName = $"{unionBaseName}Union";

        sb.AppendLine($"            var {varName}Result = {CompiledConfigNamespace}.{unionTypeName}.ExtractUnion({varName}Syntax, context, policyName);");
        sb.AppendLine($"            if ({varName}Result.IsSuccess)");
        sb.AppendLine("            {");
        sb.AppendLine($"                {varName} = {varName}Result.Value;");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine($"                diagnostics.AddRange({varName}Result.Diagnostics);");
        sb.AppendLine("            }");
    }

    private void EmitCollectionExtraction(
        StringBuilder sb,
        PropertyInfo prop,
        string varName,
        Dictionary<string, ConfigInfo> configLookup,
        Dictionary<string, List<ConfigInfo>> interfaceImplLookup)
    {
        var elementType = prop.CollectionElementType ?? "object";
        var simpleElementType = GetSimpleTypeName(elementType);

        sb.AppendLine($"            var {varName}List = new global::System.Collections.Generic.List<{GetCollectionElementOutputType(prop)}>();");
        sb.AppendLine($"            var {varName}Expressions = {varName}Syntax switch");
        sb.AppendLine("            {");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.CSharp.Syntax.ArrayCreationExpressionSyntax arr => arr.Initializer?.Expressions ?? [],");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.CSharp.Syntax.ImplicitArrayCreationExpressionSyntax impl => impl.Initializer.Expressions,");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.CSharp.Syntax.CollectionExpressionSyntax coll => coll.Elements.OfType<global::Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionElementSyntax>().Select(e => e.Expression),");
        sb.AppendLine($"                _ => global::System.Linq.Enumerable.Empty<global::Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax>()");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"            foreach (var itemExpr in {varName}Expressions)");
        sb.AppendLine("            {");

        if (prop.CollectionElementIsCompiledConfig)
        {
            // Check if it's an abstract base class
            if (configLookup.TryGetValue(simpleElementType, out var elementConfig) && elementConfig.IsAbstract)
            {
                EmitAbstractCollectionElementExtraction(sb, prop, varName, simpleElementType, configLookup);
            }
            else
            {
                sb.AppendLine($"                var itemResult = {CompiledConfigNamespace}.{simpleElementType}.ExtractFromExpression(itemExpr, context, policyName);");
                sb.AppendLine($"                if (itemResult.IsSuccess)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {varName}List.Add(itemResult.Value);");
                sb.AppendLine("                }");
                sb.AppendLine("                else");
                sb.AppendLine("                {");
                sb.AppendLine($"                    diagnostics.AddRange(itemResult.Diagnostics);");
                sb.AppendLine("                }");
            }
        }
        else if (prop.IsExpressionAllowed)
        {
            sb.AppendLine($"                var itemResult = {CompilingNamespace}.ExpressionProcessor.ProcessToExpressionValue<{elementType}>(itemExpr, context);");
            sb.AppendLine($"                if (itemResult.IsSuccess)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    {varName}List.Add(itemResult.Value);");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine($"                    diagnostics.AddRange(itemResult.Diagnostics);");
            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine($"                var itemResult = {CompilingNamespace}.ExpressionProcessor.Process(itemExpr, context);");
            sb.AppendLine($"                if (itemResult.IsSuccess)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    {varName}List.Add(itemResult.Value);");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine($"                    diagnostics.AddRange(itemResult.Diagnostics);");
            sb.AppendLine("                }");
        }

        sb.AppendLine("            }");
        sb.AppendLine($"            {varName} = {varName}List;");
    }

    private void EmitAbstractCollectionElementExtraction(
        StringBuilder sb,
        PropertyInfo prop,
        string varName,
        string abstractTypeName,
        Dictionary<string, ConfigInfo> configLookup)
    {
        // Find all derived types
        var derivedTypes = configLookup.Values
            .Where(c => c.BaseTypeName == abstractTypeName && !c.IsAbstract)
            .ToList();

        sb.AppendLine($"                var typeName = (itemExpr as global::Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax)?.Type.ToString() ?? \"\";");
        sb.AppendLine($"                {CompiledConfigNamespace}.{abstractTypeName}? itemValue = typeName switch");
        sb.AppendLine("                {");

        foreach (var derived in derivedTypes)
        {
            sb.AppendLine($"                    \"{derived.ClassName}\" => {CompiledConfigNamespace}.{derived.ClassName}.ExtractFromExpression(itemExpr, context, policyName).Match(v => ({CompiledConfigNamespace}.{abstractTypeName}?)v, _ => null),");
        }

        sb.AppendLine($"                    _ => null");
        sb.AppendLine("                };");
        sb.AppendLine($"                if (itemValue is not null)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    {varName}List.Add(itemValue);");
        sb.AppendLine("                }");
    }

    private string GetPropertyType(PropertyInfo prop)
    {
        if (prop.IsCollection && prop.CollectionElementType is not null)
        {
            var elementType = GetCollectionElementOutputType(prop);
            var collectionType = $"global::System.Collections.Generic.IReadOnlyList<{elementType}>";
            return prop.IsNullable ? $"{collectionType}?" : collectionType;
        }

        if (prop.IsInterface)
        {
            var interfaceName = GetSimpleTypeName(prop.TypeFullName);
            var unionBaseName = interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1)
                : interfaceName;
            var unionType = $"{CompiledConfigNamespace}.{unionBaseName}Union";
            return prop.IsNullable ? $"{unionType}?" : unionType;
        }

        if (prop.IsNestedCompiledConfig)
        {
            var configType = $"{CompiledConfigNamespace}.{GetSimpleTypeName(prop.TypeFullName)}";
            return prop.IsNullable ? $"{configType}?" : configType;
        }

        if (prop.IsExpressionAllowed)
        {
            var exprType = $"{AuthoringNamespace}.ExpressionValue<{prop.TypeFullName}>";
            return prop.IsNullable ? $"{exprType}?" : exprType;
        }

        return prop.IsNullable ? $"{prop.TypeFullName}?" : prop.TypeFullName;
    }

    private string GetCollectionElementOutputType(PropertyInfo prop)
    {
        var elementType = prop.CollectionElementType ?? "object";

        if (prop.CollectionElementIsCompiledConfig)
        {
            return $"{CompiledConfigNamespace}.{GetSimpleTypeName(elementType)}";
        }

        if (prop.IsExpressionAllowed)
        {
            return $"{AuthoringNamespace}.ExpressionValue<{elementType}>";
        }

        return elementType;
    }

    private static string GetSimpleTypeName(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        var name = lastDot >= 0 ? fullName.Substring(lastDot + 1) : fullName;
        if (name.StartsWith("global::"))
        {
            name = name.Substring(8);
        }
        return name;
    }

    /// <summary>
    /// Gets all properties for a config including inherited properties from base classes.
    /// Properties are returned base-first to ensure proper initialization order.
    /// </summary>
    private IReadOnlyList<PropertyInfo> GetAllProperties(ConfigInfo config, Dictionary<string, ConfigInfo> configLookup)
    {
        var properties = new List<PropertyInfo>();
        var current = config;

        // Walk up the inheritance hierarchy collecting properties (base first)
        var hierarchy = new List<ConfigInfo>();
        while (current is not null)
        {
            hierarchy.Add(current);
            if (current.BaseTypeName is not null && configLookup.TryGetValue(current.BaseTypeName, out var baseConfig))
            {
                current = baseConfig;
            }
            else
            {
                current = null;
            }
        }

        // Reverse to get base-first order
        hierarchy.Reverse();

        // Track already-seen property names to avoid duplicates from overrides
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var ancestor in hierarchy)
        {
            foreach (var prop in ancestor.Properties)
            {
                if (seen.Add(prop.Name))
                {
                    properties.Add(prop);
                }
            }
        }

        return properties;
    }
}
