// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits Args records for policies with direct method parameters (no config class).
/// </summary>
internal class MethodArgsEmitter
{
    private const string ExpressionValueType = "Microsoft.Azure.ApiManagement.PolicyToolkit.Authoring.ExpressionValue";

    public string Emit(string ns, string policyName, List<ParameterInfo> parameters)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Compiled args record for {policyName} policy.");
        sb.AppendLine("/// </summary>");
        sb.Append($"public sealed record {policyName}Args(");

        var paramStrings = new List<string>();
        foreach (var param in parameters)
        {
            var wrappedType = WrapType(param);
            paramStrings.Add($"{wrappedType} {param.Name}");
        }

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");

        return sb.ToString();
    }

    private string WrapType(ParameterInfo param)
    {
        var wrappedType = $"{ExpressionValueType}<{param.TypeFullName}>";
        return param.IsNullable ? $"{wrappedType}?" : wrappedType;
    }
}

/// <summary>
/// Information about a method parameter.
/// </summary>
internal record ParameterInfo(
    string Name,
    string TypeFullName,
    bool IsNullable
);
