// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits discriminated union types for interfaces with multiple implementations.
/// </summary>
internal class UnionTypeEmitter
{
    public string Emit(INamedTypeSymbol interfaceSymbol, List<ConfigInfo> implementations)
    {
        var sb = new StringBuilder();
        var ns = interfaceSymbol.ContainingNamespace.ToDisplayString();
        var interfaceName = interfaceSymbol.Name;

        // Generate union type name by removing "I" prefix
        var unionName = interfaceName;
        if (unionName.StartsWith("I", StringComparison.Ordinal) && unionName.Length > 1 && char.IsUpper(unionName[1]))
        {
            unionName = unionName.Substring(1);
        }
        unionName = $"{unionName}Union";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Discriminated union for implementations of <see cref=\"{interfaceName}\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal abstract class {unionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private {unionName}() {{ }}");
        sb.AppendLine();

        // Generate case classes
        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Case for <see cref=\"{impl.ClassName}\"/>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    internal sealed class {caseName} : {unionName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Gets the compiled config.</summary>");
            sb.AppendLine($"        public {impl.ClassName}CompiledConfig Config {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Creates a new {caseName} case.</summary>");
            sb.AppendLine($"        public {caseName}({impl.ClassName}CompiledConfig config)");
            sb.AppendLine("        {");
            sb.AppendLine("            Config = config;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Generate Match method
        EmitMatchMethod(sb, unionName, implementations);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitMatchMethod(StringBuilder sb, string unionName, List<ConfigInfo> implementations)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Pattern matches on the union type.");
        sb.AppendLine("    /// </summary>");
        sb.Append($"    public TResult Match<TResult>(");

        var parameters = new List<string>();
        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }
            var paramName = ToCamelCase(caseName);
            parameters.Add($"global::System.Func<{impl.ClassName}CompiledConfig, TResult> on{caseName}");
        }

        sb.Append(string.Join(", ", parameters));
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        return this switch");
        sb.AppendLine("        {");

        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }
            sb.AppendLine($"            {caseName} c => on{caseName}(c.Config),");
        }

        sb.AppendLine("            _ => throw new global::System.InvalidOperationException($\"Unknown union case: {GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
