// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Microsoft.Azure.ApiManagement.PolicyToolkit.Generators;

/// <summary>
/// Emits discriminated union types for interfaces with multiple implementations.
/// Includes ExtractUnion() method for reflection-free extraction.
/// </summary>
internal class UnionTypeEmitter
{
    private const string CompiledConfigNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling.Configs";
    private const string CompilingNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling";
    private const string ResultsNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Results";
    private const string DiagnosticsNamespace = "Microsoft.Azure.ApiManagement.PolicyToolkit.Compiling.Diagnostics";

    public string Emit(INamedTypeSymbol interfaceSymbol, List<ConfigInfo> implementations)
    {
        var sb = new StringBuilder();
        var interfaceName = interfaceSymbol.Name;

        var unionName = interfaceName;
        if (unionName.StartsWith("I", StringComparison.Ordinal) && unionName.Length > 1 && char.IsUpper(unionName[1]))
        {
            unionName = unionName.Substring(1);
        }
        unionName = $"{unionName}Union";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {CompiledConfigNamespace};");
        sb.AppendLine();
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"PolicyConfigGenerator\", \"1.0.0\")]");
        sb.AppendLine($"public abstract class {unionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private {unionName}() {{ }}");
        sb.AppendLine();

        // Generate case classes
        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }

            sb.AppendLine($"    public sealed class {caseName} : {unionName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {impl.ClassName} Config {{ get; }}");
            sb.AppendLine($"        public {caseName}({impl.ClassName} config) => Config = config;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Generate Match method
        EmitMatchMethod(sb, unionName, implementations);
        sb.AppendLine();

        // Generate ExtractUnion method
        EmitExtractUnionMethod(sb, unionName, implementations);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void EmitMatchMethod(StringBuilder sb, string unionName, List<ConfigInfo> implementations)
    {
        sb.Append($"    public TResult Match<TResult>(");

        var parameters = new List<string>();
        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }
            parameters.Add($"global::System.Func<{impl.ClassName}, TResult> on{caseName}");
        }

        sb.Append(string.Join(", ", parameters));
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        return this switch");
        sb.AppendLine("        {");

        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }
            sb.AppendLine($"            {caseName} c => on{caseName}(c.Config),");
        }

        sb.AppendLine($"            _ => throw new global::System.InvalidOperationException($\"Unknown union case: {{GetType().Name}}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private void EmitExtractUnionMethod(StringBuilder sb, string unionName, List<ConfigInfo> implementations)
    {
        sb.AppendLine($"    public static {ResultsNamespace}.Result<{unionName}> ExtractUnion(");
        sb.AppendLine($"        global::Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression,");
        sb.AppendLine($"        {CompilingNamespace}.ICompilationContext context,");
        sb.AppendLine($"        string policyName)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (expression is not global::Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax objectCreation)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return {ResultsNamespace}.Result<{unionName}>.Failure(");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.Diagnostic.Create(");
        sb.AppendLine($"                    {DiagnosticsNamespace}.CompilationErrors.PolicyArgumentIsNotAnObjectCreation,");
        sb.AppendLine($"                    expression.GetLocation(),");
        sb.AppendLine($"                    policyName,");
        sb.AppendLine($"                    \"{unionName}\"));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var typeName = objectCreation.Type.ToString();");
        sb.AppendLine("        return typeName switch");
        sb.AppendLine("        {");

        foreach (var impl in implementations)
        {
            var caseName = impl.ClassName;
            if (caseName.EndsWith("Config", StringComparison.Ordinal))
            {
                caseName = caseName.Substring(0, caseName.Length - 6);
            }

            sb.AppendLine($"            \"{impl.ClassName}\" => {impl.ClassName}.ExtractFromExpression(expression, context, policyName)");
            sb.AppendLine($"                .Map(c => ({unionName})new {caseName}(c)),");
        }

        sb.AppendLine($"            _ => {ResultsNamespace}.Result<{unionName}>.Failure(");
        sb.AppendLine($"                global::Microsoft.CodeAnalysis.Diagnostic.Create(");
        sb.AppendLine($"                    {DiagnosticsNamespace}.CompilationErrors.PolicyArgumentIsNotOfRequiredType,");
        sb.AppendLine($"                    expression.GetLocation(),");
        sb.AppendLine($"                    policyName,");
        sb.AppendLine($"                    typeName))");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }
}
